### ISSUE TITLE
copy and move

### ISSUE THREAD

**Issue by wrigleyster** [gigagg/GiGaSdk#2]
Hi,
Thanks for the great SDK.
I've been playing around with making a native file browser.. One thing though, I can't seem to figure out: How do you copy/move files and folders? If I knew how to copy, I could copy and remove the old node to perform move, but how do you copy?

I tried setting the parentId
```c++
// FolderNode dest; Node original_node;
auto copy = Node::create(original_node);
copy->handle()->parentId = dest->id
```
but that didn't seem to do anything..

Sorry, if this is the wrong place to post a question such as this.. I wasn't sure where to ask.

Cheers, W

**Comment by gigagg** [comment]
This is the correct place to ask this kind of questions.

For now, there is no easy way to do copy/move operations.

I may be able to hack something and push it in the next 24 hours.
I'll keep you posted.

**Comment by gigagg** [comment]
Implementing the copy/move operation is a bit more complicated than expected.
I expect to be able to deliver it at the beginning of next week.

**Comment by wrigleyster** [comment]
no worries, there is no rush :) I have other avenues I can pursue in the meanwhile.

Thanks for looking into this :D
